### ISSUE TITLE
[Bug] Assertion error when running example on 2 nvidia rtx 4090

### ISSUE THREAD

**Issue by zydmtaichi** [xhuangcv/humannorm#20]
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/sdb/humannorm/launch.py", line 237, in <module>
[rank1]:     main(args, extras)
[rank1]:   File "/mnt/sdb/humannorm/launch.py", line 180, in main
[rank1]:     trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
[rank1]:     call._call_and_handle_interrupt(
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank1]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank1]:     return function(*args, **kwargs)
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
[rank1]:     self._run(model, ckpt_path=ckpt_path)
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
[rank1]:     call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 102, in _call_setup_hook
[rank1]:     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
[rank1]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 189, in _call_lightning_datamodule_hook
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/mnt/sdb/humannorm/threestudio/data/multiview.py", line 543, in setup
[rank1]:     self.val_dataset = MultiviewTestDataset(self.cfg, "val")
[rank1]:   File "/mnt/sdb/humannorm/threestudio/data/multiview.py", line 417, in __init__
[rank1]:     assert len(camera_dict["frames"]) == self.cfg.n_views
[rank1]: AssertionError
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/sdb/humannorm/launch.py", line 237, in <module>
[rank0]:     main(args, extras)
[rank0]:   File "/mnt/sdb/humannorm/launch.py", line 180, in main
[rank0]:     trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
[rank0]:     call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 102, in _call_setup_hook
[rank0]:     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
[rank0]:   File "/mnt/sdb/conda/envs/hunorm/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 189, in _call_lightning_datamodule_hook
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/mnt/sdb/humannorm/threestudio/data/multiview.py", line 543, in setup
[rank0]:     self.val_dataset = MultiviewTestDataset(self.cfg, "val")
[rank0]:   File "/mnt/sdb/humannorm/threestudio/data/multiview.py", line 417, in __init__
[rank0]:     assert len(camera_dict["frames"]) == self.cfg.n_views
[rank0]: AssertionError
```

**Comment by zydmtaichi** [comment]
@xhuangcv
